# define scoring mesh
/score/create/cylinderMesh cylinderMesh_1
/score/mesh/cylinderSize 50 1 cm
/score/mesh/nBin 30 1 30
/score/mesh/translate/xyz 0. 0. 20. cm

/score/quantity/flatSurfaceCurrent currentNeutron 1
/score/quantity/flatSurfaceFlux fluxNeutron 1
/score/quantity/nOfStep nOfStepNeutron
/score/quantity/nOfTrack nOfTrackNeutron
/score/quantity/trackLength trackLengthNeutron
/score/filter/particle neutronFilter neutron

/score/close
